version: '3.8'

services:
  database:
    image: mariadb:latest
    container_name: symfoniak_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony_password
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: symfoniak_redis
    ports:
      - "6379:6379"
