controllers:
  resource:
    path: ../src/Domain/Controller/
    namespace: App\Domain\Controller
  type: attribute

app_login:
  path: /login
  controller: App\Domain\Controller\LoginController::login

app_logout:
  path: /logout
